/**
 * Grasp Google Sheets Extension - TypeScript Version
 * Auto-generated by Rollup
 */

/**
 * Called when the spreadsheet is opened
 */
function onOpen(): void {
  SpreadsheetApp.getUi()
    .createAddonMenu()
    .addItem('🚀 Launch Grasp', 'launchGrasp')
    .addItem('📊 Validate Data', 'validateData')
    .addToUi();
}

/**
 * Main Grasp function
 */
function launchGrasp(): void {
  console.log('🚀 GRASP: TypeScript version launching...');
  SpreadsheetApp.getUi().alert('✅ Grasp TypeScript Extension Works!');
  
  // Get current sheet info
  const sheet = SpreadsheetApp.getActiveSheet();
  const range = sheet.getDataRange();
  const values = range.getValues();
  
  console.log(`📊 Sheet: ${sheet.getName()}, Rows: ${values.length}`);
}

/**
 * Validate data function
 */
function validateData(): void {
  console.log('📊 GRASP: Validating data...');
  SpreadsheetApp.getUi().alert('🔍 Data validation feature coming soon!');
}
